# See: https://www.mkdocs.org/user-guide/configuration/
---
# Site configuration:
site_name: Aurora Documentation
site_author: NEAR Protocol
site_url: https://doc.aurora.dev
repo_name: aurora-is-near/doc.aurora.dev
repo_url: https://github.com/aurora-is-near/doc.aurora.dev
google_analytics:

# Content configuration:
remote_name: origin
docs_dir: content
site_dir: public
use_directory_urls: false

# Table of contents (TOC):
nav:
  - Overview: index.md
  #- Learn:
  #  - Connecting a Wallet:
  #    - MetaMask: learn/connect/metamask.md
  #    - WalletConnect: learn/connect/walletconnect.md
  #  - Bridging Funds:
  #    - ETH Balances: learn/bridge/eth.md
  #    - ERC-20 Tokens: learn/bridge/erc-20.md
  #  - Deploying a Contract:
  #    - Using Remix: learn/deploy/remix.md
  #    - Using Hardhat: learn/deploy/hardhat.md
  #    - Using Truffle: learn/deploy/truffle.md
  #  - Interacting with Contracts:
  #    - Using Remix: learn/interact/remix.md
  - Develop:
    - Networks: develop/networks.md
    - FAQs: develop/faq.md
    #- Getting Started:
    #  - MetaMask: develop/start/metamask.md
    #  - Truffle: develop/start/truffle.md
    #  - Hardhat: develop/start/hardhat.md
    - Compatibility:
      - JSON-RPC: develop/compat/rpc.md
      - EVM: develop/compat/evm.md
    - Resources:
      - Changelog: develop/changelog.md
      - Roadmap: develop/roadmap.md
      - Glossary: develop/glossary.md
  #- Integrate: integrate/index.md

# Theme configuration:
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  favicon: _img/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
  custom_dir: theme

# Markdown configuration:
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Plugin configuration:
plugins:
  - search
  - macros
  - mermaid2:
      arguments:
        theme: neutral

# Custom CSS configuration:
extra_css:
  - _css/extra.css

# Custom JS configuration:
extra_javascript:
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  - _js/extra.js

# Footer configuration:
extra:
  generator: false
  social:
    - name: Aurora on GitHub
      icon: fontawesome/brands/github
      link: https://github.com/aurora-is-near
    - name: Aurora on Discourse
      icon: fontawesome/brands/discourse
      link: https://gov.near.org/c/dev/aurora/46
    - name: Aurora on Discord
      icon: fontawesome/brands/discord
      link: https://discord.gg/jNjHYUF8vw
    - name: Aurora on Telegram
      icon: fontawesome/brands/telegram
      link: https://t.me/auroraisnear
    - name: Aurora on Stack Overflow
      icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/aurora+near
    - name: Aurora on Twitter
      icon: fontawesome/brands/twitter
      link: https://twitter.com/auroraisnear
